
# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.42.0"

default_platform :ios


platform :ios do

  desc "Setup and Run Tests"
  before_all do
    ENV['KEYCHAIN_NAME'] = "TempKeychain2.keychain"

    scan(
        workspace: "IMMSlackerClient.xcworkspace",
        scheme: "IMMSlackerClientXCTool",
        device: "iPhone 6",
        clean: true,
        code_coverage: true,
        configuration: "Debug",
        xcargs: "ENABLE_BITCODE=NO",
        output_directory: "./build",
        slack_url: ENV['SLACK_URL'],
        slack_channel: "internationalmixmob"
    )

  end

  desc "Run Tests"
  lane :test do

    xctool :test, [
      "--project", "IMMSlackerClient.xcodeproj",
      "--scheme", "IMMSlackerClientXCTool”,
      "--configuration", "Debug",
      "--sdk", "iphonesimulator",
      "--arch", "i386",
      "OBJROOT=./build",
      "ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES ENABLE_BITCODE=NO"
    ].join(" ")

    gcovr(
      print_summary: true,
      html: true,
      html_details: true,
      exclude: ".*Test.*",
      output: "build/code-coverage/report.html"
    )

    gcovr(
      xml: true,
      exclude: "'.*Test.*''",
      output: "build/code-coverage/report.xml"
    )

  end

  desc "Submit a new Beta Build"
  desc "This will also make sure the profile is up to date"
  lane :build do
    sh "scripts/decrypt-files.sh"
    #increment_build_number
    import_certificates
    cert
    sigh(
      force: true,
      skip_install: true,
      filename: 'fastlane/profiles/educscie71immapp_AppStore.mobileprovision'
    )

    sh "./fl-framework-build.sh"

  end

  desc "Deploy a new version to the App Store"
  lane :deploy do

  end

  desc "Deploy a new version to the App Store"
  lane :none do

  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    slack(
       message: exception.message,
       success: false
     )
  end

  # SHARED FUNCTIONS
  def import_certificates
    return unless Helper.is_ci? # As in my local machine I don't need to import the certificates, only run if it's in the CI

    create_keychain(
      name: ENV["KEYCHAIN_NAME"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true,
      password: ENV["KEY_PASSWORD"]
    )

    import_certificate(
      certificate_path: "fastlane/certs/ios_distribution.p12",
      certificate_password: ENV['ENCRYPTION_SECRET'],
      keychain_name: ENV["KEYCHAIN_NAME"]
    )

  #  import_certificate(
  #    certificate_path: "fastlane/certs/ios_distribution.cer",
  #    keychain_name: ENV["KEYCHAIN_NAME"]
  #  )
  end

end
