source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.1'
use_frameworks!

pod 'Starscream', '1.0.2'
pod 'Alamofire', '~> 3.0.0-beta.3'
pod 'SwiftyJSON', '2.2.1'
pod 'JSQMessagesViewController', '7.1.0'